apiVersion: v1
kind: Pod
metadata:
  name: kube2py
  namespace: mateapp
  labels:
    app: kube2py
spec:
  containers:
    - name: kube2py
      image: salo2452/kube2py:1.3.0
      imagePullPolicy: Always
      env:
      - name: EXTERNAL_ENDPOINT
        value: http://httpbin-api.mateapp.svc.cluster.local
      ports:
      - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5

---

apiVersion: v1
kind: Pod
metadata:
  name: kube2py-1
  namespace: mateapp
  labels:
    app: kube2py
spec:
  containers:
    - name: kube2py
      image: salo2452/kube2py:1.3.0
      imagePullPolicy: Always
      env:
      - name: EXTERNAL_ENDPOINT
        value: http://httpbin-api.mateapp.svc.cluster.local
      ports:
      - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
