apiVersion: v1
kind: Pod
metadata:
    name: busybox
    namespace: mateapp
spec:
    containers:
    - name: curl-container
      image: curlimages/curl:latest
      args:
      - sleep
      - "1000"
