apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
  namespace: mateapp
spec:
  storageClassName: standard
#  Retain означає, що сховище треба залишити для ручного видалення (ми використаємо це значення).
#  Delete означає, що сховище буде автоматично видалене.
  persistentVolumeReclaimPolicy: Retain
#  ReadWriteOnce означає, що сховище може бути використане лише на одній ноді в кластері.
#  ReadWriteMany означає, що сховище може бути використане на різних нодах. Наші поди будуть на двох нодах і всі вони будуть читати з цього сховища і писати у це сховище, тому ми використаємо саме це значення.
#  ReadOnlyMany означає, що сховище можна використовувати в режимі читання з різних нод.
#  ReadWriteOncePod вийшло у бета-версії наприкінці 2023 року. Дозволяє лише одному поду на весь кластер використати сховище для читання і запису.
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/