apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube2py
  namespace: mateapp
  labels:
    app: kube2py
spec:
  selector:
    matchLabels:
      app: mate-server
  template:
    metadata:
      labels:
        app: mate-server
    spec:
      containers:
        - name: mate-server
          image: nginx:alpine
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          ports:
            - containerPort: 80
              hostPort: 30008

