global:
  ENVIRONMENT: "Production"

kube2py:

 configs:
  APP_ENV: "testing_helm-Staging"

 secrets:
   password: MyStrongerPassword
   login: SuperSuperUser



 image:
   name: kube2py
   repository: ikulyk404/kube2py
   version: 2.0.0
 resources:
   requests:
      memory: "256Mi"
      cpu: "100m"
   limits:
     memory: "256Mi"
     cpu: "100m"
 hpa:
   enabled: true
   minReplicas: 3
   maxReplicas: 5

