apiVersion: v1
kind: Pod
metadata:
    name: busybox
    namespace: mateapp
    labels:
      app: busybox
spec:
    containers:
    - name: curl-container
      image: curlimages/curl:latest
      args:
      - sleep
      - "1000"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
           - matchExpressions:
              - key: "utility"
                operator: In
                values:
                - "busybox"


