apiVersion: v1
kind: Service
metadata:
  name: kube2py-nodeport-service
  namespace: mateapp
spec:
  type: NodePort
  selector:
    app: kube2py
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
