apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-lister
  namespace: mateapp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-lister
  namespace: mateapp
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-lister-binding
  namespace: mateapp
subjects:
- kind: ServiceAccount
  name: pod-lister
  namespace: mateapp
roleRef:
  kind: Role
  name: pod-lister
  apiGroup: rbac.authorization.k8s.io
