# this config file contains all config fields with comments
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
  - |
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    evictionHard:
      nodefs.available: "0%"

# patch it further using a JSON 6902 patch
kubeadmConfigPatchesJSON6902:
  - group: kubeadm.k8s.io
    version: v1beta3
    kind: ClusterConfiguration
    patch: |
      - op: add
        path: /apiServer/certSANs/-
        value: my-hostname
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /tmp
        containerPath: /data
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30007
        hostPort: 30007
      - containerPort: 30008
        hostPort: 30008
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP

  # the workers
  - role: worker
    labels:
      app: kube2py
    extraMounts:
      - hostPath: /tmp
        containerPath: /data

  - role: worker
    labels:
      app: kube2py
    extraMounts:
      - hostPath: /tmp
        containerPath: /data

  - role: worker
    labels:
      app: kube2py
    extraMounts:
      - hostPath: /tmp
        containerPath: /data

  - role: worker
    labels:
      app: kube2py
    extraMounts:
      - hostPath: /tmp
        containerPath: /data
