apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "MTIzNA==" # Base64 endcoding from "1234"
  MYSQL_USER: "YXBwX3VzZXI=" # Base64 endcoding from "app_user"
  MYSQL_PASSWORD: "MTIzNA==" # Base64 endcoding from "1234"
  # mysql -h mysql-0.mysql -u root --password=1234 -e "INSERT INTO app_db.counter VALUE(1,1)"
  # mysql -h mysql-0.mysql -u root --password=1234 -e "SELECT * FROM app_db.counter"
  # kubectl run mysql-client --image=mysql:8.0 -it -n mysql -- sh
  # kubectl exec mysql-client -it -n mysql -- sh